// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "HalibutTracking.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class HalibutTrackingHandler : virtual public HalibutTrackingIf {
 public:
  HalibutTrackingHandler() {
    // Your initialization goes here
  }

  int32_t GetCatchInPoundsToday() {
    // Your implementation goes here
    printf("GetCatchInPoundsToday\n");
  }

  int32_t GetCatchInPoundsByDate(const Date& d, const double t) {
    // Your implementation goes here
    printf("GetCatchInPoundsByDate\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<HalibutTrackingHandler> handler(new HalibutTrackingHandler());
  ::std::shared_ptr<TProcessor> processor(new HalibutTrackingProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

